import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

import Layout from '../containers/Layout/Layout.container';
import Main from '../containers/Main/Main.container';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Relax Frens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout>
          <Main />
        </Layout>

      </main>

    </div>
  )
}
